 <?php if ($posts = $this->wordpresshomelist()): ?>  
                            
    <div class="R_content">
<?php $i=0; foreach ($posts as $post): ?>
         <?php $i++; if ($i > 1){ break;} ?>  
      <div class="w_pjrm">
          <a href="<?php echo $this->getUrl(); ?>news/pinjiu-rumen/" ><span>品酒入门</span></a>
          <a class="more" rel="nofollow" href="<?php echo $this->getUrl(); ?>news/pinjiu-rumen/">更多>></a>
      </div>
      <div class="R_top">
        <ul>
          <li> 
          <?php if ($featuredImage = $post->getFeaturedImage()): ?>
							<img src="<?php echo $featuredImage->getGuid() ?>" alt=""/>
                <?php else: ?>
                 <img src="<?php echo $this->getUrl().'media/mr_pic'.$i.'.gif';?>" alt="" /> 
					<?php endif; ?> 
          
          </li>
          <li class="desc">
            <a href="<?php echo $post->getPermalink(); ?>/"><h5><?php echo $post->getPostTitle(); ?></h5></a>
            <?php $description = $this->description($post->getId()); ?> 
            <?php foreach($description->getData() as $descrip): ?>
            <p><?php echo Mage::helper('core/string')->cut_str($descrip['meta_value'],60); ?>&hellip;</p>
            <?php endforeach; ?>
            <a class="R_top_detail" href="<?php echo $post->getPermalink(); ?>/">[详细]</a>
          </li>
          
        </ul>
      </div>
     <?php endforeach; ?> 
      <div class="R_bottom">
        <ul>
        <?php $i=0; foreach ($posts as $post): ?>
          <?php $i++; if ($i <= 1){continue;}
          if ($i > 5){ break;} 
          ?> 
          <li> <span class="author"> <a href="<?php echo $post->getPermalink(); ?>/" target="_blank"></a><span class="date"><?php echo $post->getPostDate(); ?></span> </span> <a href="<?php echo $post->getPermalink(); ?>" target="_blank"><?php echo $post->getPostTitle(); ?> </a> </li>
        <?php endforeach; ?>
        
        </ul>
      </div>
    </div>

<?php endif; ?>