 <?php if ($posts = $this->wordpresshomelist()): ?>                               
<div class="ysbj_right">
  <div class="Romantic_content"><h2>
      <a href="<?php echo $this->getUrl(); ?>news/hongjiu-meishi/"><span>红酒美食
      </span></a> 
      <img src="<?php echo $this->getUrl().'media/Romantic_title.gif';?>" alt="" />
      <a class="more" rel="nofollow" href="<?php echo $this->getUrl(); ?>news/hongjiu-meishi/">更多>></a>
      </h2>
    <div class="R_content">
  <?php $i=0; foreach ($posts as $post): ?>
  <?php $i++; if ($i > 1){break;} ?> 
      <div class="R_top">
        <ul>
          <li class="desc">
            <a href="<?php echo $post->getPermalink(); ?>/"><h5><?php echo $post->getPostTitle(); ?></h5></a>
            <?php $description = $this->description($post->getId()); ?>
          <?php foreach($description->getData() as $descrip): ?>
          <p><?php echo Mage::helper('core/string')->cut_str($descrip['meta_value'],60); ?>&hellip;</p>
          <?php endforeach; ?>
            <a class="R_top_detail" href="<?php echo $post->getPermalink(); ?>/">[详细]</a>
          </li>
          <li> 
           
          <?php if ($featuredImage = $post->getFeaturedImage()): ?>
								<img src="<?php echo $featuredImage->getGuid() ?>" alt=""/>
                <?php else: ?>
                <img src="<?php echo $this->getUrl().'media/mr_pic'.$i.'.gif';?>" alt="" />
					<?php endif; ?>
          </li>
        </ul>
      </div>
     <?php endforeach; ?> 
      <div class="R_bottom">
        <ul>
      <?php $i=0; foreach ($posts as $post): ?>
      <?php $i++; if ($i <= 1){continue;}
     if ($i > 6){break;} ?> 
          <li> 
          <span class="author"> 
            <a href="<?php echo $post->getPermalink(); ?>/" target="_blank"></a> 
            <span class="date"><?php echo $post->getPostDate(); ?></span>
          </span> 
            <a href="<?php echo $post->getPermalink(); ?>/" target="_blank"><?php echo $post->getPostTitle(); ?> </a> 
          </li>
          <?php endforeach; ?>
         
        </ul>
      </div>
    </div>
  </div>
</div>
<?php endif; ?>
