 

 <?php if ($posts = $this->wordpresshomelist()): ?>                               
<div class="ysbj_right">
  <div class="Romantic_content"><h1>
      <span>红酒禁忌
      </span> 
      <img src="<?php echo $this->getUrl().'media/yjjj_pic'.$i.'.gif';?>" alt="" /></h1>
    <div class="R_content">
                   <?php $i=0; foreach ($posts as $post): ?>
         <?php 
     $i++; 
     if ($i > 1){
         break;
     } ?> 
      <div class="R_top">
        <ul>
          <li class="desc">
            <a href="<?php echo $post->getPermalink(); ?>/">
<h5><?php echo $post->getPostTitle(); ?></h5>
</a>
        <?php $description = $this->description($post->getId()); ?>
          <?php foreach($description->getData() as $descrip): ?>
          <p><?php echo Mage::helper('core/string')->cut_str($descrip['meta_value'],60); ?></p>
          <?php endforeach; ?>
          </li>
          <li> 
          <img src="<?php echo $this->getUrl().'media/mr_pic'.$i.'.gif';?>" alt="" /> 
          </li>
        </ul>
      </div>
     <?php endforeach; ?> 
      <div class="R_bottom">
        <ul>
                  <?php $i=0; foreach ($posts as $post): ?>
               <?php 
     $i++; 
          if ($i <= 1){
         continue;;
     }
     if ($i > 6){
         break;
     } ?> 
<li> <span class="author"> <a href="<?php echo $post->getPermalink(); ?>/" target="_blank"><span class="date"><?php echo $post->getPostDate(); ?></span></a> </span> <a href="<?php echo $post->getPermalink(); ?>/" target="_blank"><?php echo $post->getPostTitle(); ?> </a> </li>
          <?php endforeach; ?>
         
        </ul>
      </div>
    </div>
  </div>
</div>
<?php endif; ?>