<?php if ($posts = $this->wordpresshomelist()): ?> 

  <?php $i=0; foreach ($posts as $post): ?>
  <?php $i++; if ($i > 1){break;} ?> 
  <div class="ls_img">
  <?php if ($featuredImage = $post->getFeaturedImage()): ?>
								<img src="<?php echo $featuredImage->getGuid() ?>" alt=""/>
                <?php else: ?>
                <img src="<?php echo $this->getUrl().'media//itxt_img.gif'; ?>" alt="" />
					<?php endif; ?>
  </div>
  <?php endforeach; ?>
  <?php $i=0; foreach ($posts as $post): ?>
  <?php $i++; if ($i > 4){ break; } ?> 
  
    <li class="title"><a href="<?php echo $post->getPermalink(); ?>/"><h5><?php echo $post->getPostTitle(); ?></h5></a></li>
  <?php endforeach; ?>

<?php endif; ?>