<?php if ($posts = $this->wordpresshomelist()): ?>  
<?php $i=0; foreach ($posts as $post): ?>
<?php $i++; if ($i > 1){ break; } ?> 
<li>
  <?php if ($featuredImage = $post->getFeaturedImage()): ?>
  <img src="<?php echo $featuredImage->getGuid(); ?>" alt=""/>
  <?php else: ?>
  <img src="<?php echo $this->getUrl().'media/yjjj_img.gif'; ?>" alt="" />
  <?php endif; ?>
</li>
<li class="desc">
  <a href="<?php echo $post->getPermalink(); ?>/"><h5><?php echo $post->getPostTitle(); ?></h5></a>
  <?php $description = $this->description($post->getId()); ?>
  <?php foreach($description->getData() as $descrip): ?>
  <p><?php echo Mage::helper('core/string')->cut_str($descrip['meta_value'],60); ?></p>
  <?php endforeach; ?>
</li>
<?php endforeach; ?> 
<?php endif; ?>
