<?php if ($posts = $this->wordpresshomelist()): ?>  
<?php $i=0; foreach ($posts as $post): ?>
<?php $i++; if ($i > 1){ break; } ?> 
<li>
  <?php if ($featuredImage = $post->getFeaturedImage()): ?>
  <img src="<?php echo $featuredImage->getGuid(); ?>" alt=""/>
  <?php else: ?>
  <img src="<?php echo $this->getUrl().'media/yjjj_img.gif'; ?>" alt="" />
  <?php endif; ?>
</li>
<li class="desc">
    <ul>
        <?php $i=0; foreach ($posts as $post): ?>
          <?php $i++; if ($i <= 1){continue;}
          if ($i > 5){ break;} 
          ?> 
          <li><a href="<?php echo $post->getPermalink(); ?>/"><h5><?php echo $post->getPostTitle(); ?></h5></a> </li>
        <?php endforeach; ?>
        
     </ul>
</li>
<?php endforeach; ?> 
<?php endif; ?>
