<?php
   /**
   * @category    Fishpig
   * @package     Fishpig_Wordpress
   * @license     http://fishpig.co.uk/license.txt
   * @author      Ben Tideswell <help@fishpig.co.uk>
   */
   ?>  
<?php $post = $this->getPost() ?>
<?php //print_r($post->getData()); ?>
<?php if ($post): ?>
<?php $helper = $this->helper('wordpress') ?>
<?php $description = Mage::getResourceModel('wordpress/postmeta_collection')->addPostIdFilter($post->getId(),'_aioseop_description'); ?>
<?php $author = $post->getAuthor() ?>
<?php if ($this->helper('wordpress/plugin_shareThis')->canDisplayOnPost()): ?>
<?php echo $this->helper('wordpress/plugin_shareThis')->getJavascriptHtml() ?>
<?php endif; ?>

<div class="post-view">
  <div class="artical_main">
    <div class="page-title">
      <h1><?php echo $post->getPostTitle() ?></h1>
    </div>
    <p class="when">
      <?php echo $this->__('Posted on %s by %s', $post->getPostDate(), '<a href="'.$author->getUrl().'">'.$author->getDisplayName().'</a>') ?>
      <span>

      </span>
    </p>
  </div>
  <div class="new_contant">
    <div class="gongxiao">
      <?php if($description->getData()): ?>
      <?php foreach($description->getData() as $descrip): ?>

      <div class="first_effect">
        <?php echo $descrip['meta_value']; ?>
      </div>
      <?php endforeach; ?>

      <?php endif; ?>
      <div class="gongxiao_text">
        <div class="title">[文章正文]</div>
        <div class="entry">

          <?php echo $post->getPostContent() ?>
          <br style="clear:both;"/>
        </div>
        <?php if ($this->helper('wordpress/plugin_shareThis')->canDisplayOnPost()): ?>
        <div id="sharethis-icons"><?php echo $this->helper('wordpress/plugin_shareThis')->getIcons($post) ?></div>
        <?php endif; ?>
      </div>
    </div>
  </div>
  
  <p class="details">
  </p>
  <?php echo $this->getCommentsHtml() ?>
</div>
<?php endif; ?>
