<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<div class="std">
  <div class="ysad">
    <div class="ad_left"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('137')->toHtml() ?></div>
    <div class="mrad_right"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('120')->toHtml() ?></div>
  </div>
  
  <div class="ysbj">
    <div class="ysbj_left"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('138')->toHtml() ?></div>
    <div class="ysbj_right"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('139')->toHtml() ?></div>
  </div>
  
  <div class="zx_banner"><img src="http://www.madeinworld.cn/media/ys_banner.gif" alt="" width="1000" height="100" /></div>
  
  <div class="red_ml">
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('140')->toHtml() ?>
  </div>

  <div class="zx_banner"><img src="http://www.madeinworld.cn/media/ys_banner.gif" alt="" width="1000" height="100" /></div>
  <div class="red_con">
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('142')->toHtml() ?>
  </div>
  
  <div class="zx_banner"><img src="http://www.madeinworld.cn/media/ys_banner.gif" alt="" width="1000" height="100" /></div>
  <div class="btc_cont">
      <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('143')->toHtml() ?>
  </div>


</div>

<?php //echo $this->getPostListHtml() ?>
