<?php
/*
 * ---------------------------------------------------------------------------
 *  luochunhui.com
 *
 *     COPYRIGHT (c)  2011 BY  LuoChunhui.  ALL RIGHTS
 *     RESERVED.   The source code, design, and structure of THIS PROGRAM are trade secrets. 
 * You will not disassemble, decompile, or reverse engineer it, in whole or in part, 
 except to the extent expressly permitted by law. 
 You will not use THIS PROGRAM for illegal purposes. You will comply with all export laws. Giko_Tenpay is licensed, not sold.
 * 
 * ---------------------------------------------------------------------------
 * 
 * @package    Giko_Tenpay
 * @category   Payment
 * @author     luochunhui <wo@luochunhui.com>
 * @copyright  Copyright (c) 2011 LuoChunhui (http://www.luochunhui.com)
 *
 */
?>
<div class="page-head">
    <h3><?php echo $this->__('Error occured') ?></h3>
</div>
<p><?php echo $this->__('There was an error occurred during paying process.') ?></p>