<?php
/**
 * ---------------------------------------------------------------------------
 * luochunhui.com
 *
 * COPYRIGHT (c)  2011 BY  LuoChunhui.  ALL RIGHTS
 * RESERVED.   The source code, design, and structure of THIS PROGRAM are trade secrets. 
 * You will not disassemble, decompile, or reverse engineer it, in whole or in part, 
 except to the extent expressly permitted by law. 
 You will not use THIS PROGRAM for illegal purposes. You will comply with all export laws. Giko_Tenpay is licensed, not sold.
 *
 * @category   Payment
 * @package    Giko_Tenpay
 * @author     luochunhui
 * @copyright  Copyright (c) 2011 LuoChunhui (http://www.luochunhui.com)
 * ---------------------------------------------------------------------------
 *
 * Alipay Form Block
 */
?>
<?php

$standard = Mage::getModel('tenpay/payment');		

$form = new Varien_Data_Form();
$form->setAction($standard->getTenpayUrl())
    ->setId('tenpay_payment_checkout')
    ->setName('tenpay_payment_checkout')
    ->setMethod('POST')
    ->setUseContainer(true);
foreach ($standard->setOrder($this->getOrder())->getStandardCheckoutFormFields() as $field => $value) {
    $form->addField($field, 'hidden', array('name' => $field, 'value' => $value));
}

$formHTML = $form->toHtml();

echo $formHTML;

?>
<div class="col2-set order-info-box">
    正在为您跳转至财付通网站，请稍后...
</div>

<script type="text/javascript">
$("tenpay_payment_checkout").submit();
</script>