<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php $post = $this->getPost() ?>
<?php $comments = $this->getComments() ?>
<div id="comments">
	<?php //if ($this->getCommentCount() > 0): ?>
	<?php if ($comments->count() > 0): ?>

    <ul class="comment-list">
			<?php foreach($comments as $comment): ?>
				<li id="comment-<?php echo $comment->getId() ?>">
          <div class="commont_main">
					<div class="by">
						<a href="<?php echo $comment->getCommentAuthorUrl() ?>" rel="nofollow">
							<?php echo $comment->getCommentAuthor() ?>
						</a> 
					</div>
					<div class="entry"><?php echo nl2br($comment->getCommentContent()) ?></div>
          </div>
					<div class="when"><?php echo $this->__('%s', $comment->getCommentDate()) ?></div>
				</li>
			<?php endforeach; ?>
		</ul>
		<?php echo $this->getPagerHtml() ?>
	<?php endif; ?>
	<?php if ($this->canComment()): ?>
		<?php echo $this->getCommentFormHtml() ?>
	<?php endif; ?>
</div>