<?php

$step_counter = 1;
$helper = Mage::helper('onestepcheckout/checkout');

?>

<?php if(!$this->canCheckout() || !$this->validateMinimumAmount()): ?>
    <?php if($this->settings['checkout_title']): ?>
        <h1 class="onestepcheckout-title"><img border="0" alt="" src="<?php echo $this->getSkinUrl('images/step2.gif')?>"></h1>
    <?php endif; ?>

    <?php if($this->canCheckout() && !$this->validateMinimumAmount()): ?>
    <p><a href="<?php echo $this->getUrl(''); ?>"><?php echo $this->__('Back to homepage'); ?></a></p>
    <?php else: ?>
    <p><?php echo $this->__('You need to have products in your cart to checkout, and your cart is empty.'); ?></p>
    <p><a href="<?php echo $this->getUrl(''); ?>"><?php echo $this->__('Back to homepage'); ?></a></p>
    <?php endif; ?>
<?php else: ?>


<script type="text/javascript">
(function($) {
  $.fn.emptySelect = function() {
    return this.each(function(){
      if (this.tagName=='SELECT') this.options.length = 0;
    });
  }

  $.fn.loadSelect = function(optionsDataArray) {
    return this.emptySelect().each(function(){
      if (this.tagName=='SELECT') {
        var selectElement = this;
        $.each(optionsDataArray,function(index,optionData){
          var option = new Option(optionData.caption,
                                  optionData.caption);
           option.className=optionData.value;                       
          if ($.browser.msie) {
            selectElement.add(option);
          }
          else {
            selectElement.add(option,null);
          }
        });
      }
    });
  }
})(jQuery);

function selectbillcity() {
  
    
		var region_value =   jQuery("#billing\\:region_id option:selected").val();   
    var city =  jQuery("#billing\\:city");
    jQuery.getJSON(
     "<?php echo $this->getUrl().'cascade/index/getcity'; ?>",
     {region_id:region_value},
     function(data){
        city.loadSelect(data);
        //console.dir(data);
     }
  );  
}


function selectbilldistrict() {
  
    
		var city_value =   jQuery("#billing\\:city option:selected").attr("class");
    var district =  jQuery("#billing\\:district");
    jQuery.getJSON(
     "<?php echo $this->getUrl().'cascade/index/getdistrict'; ?>",
     {city_id:city_value},
     function(data){
        district.loadSelect(data);
       // console.dir(data);
     }
  );  
}

function selectdistrict() {
     var district_value = jQuery("#billing\\:district option:selected").val();
     jQuery("#billing\\:street1").val(district_value);
   //  var postcode = jQuery("#billing\\:district option:selected").attr("class"); 
   //  jQuery("#billing\\:postcode").val(postcode);
} 
</script> 


 

<fieldset class="group-select" style="margin: 0;">

<?php if($this->settings['checkout_title']): ?>
    <h1 class="onestepcheckout-title"><img border="0" alt="" src="<?php echo $this->getSkinUrl('images/step2.gif')?>"></h1>
<?php endif; ?>
<!--
<?php //if(!$this->isCustomerLoggedIn() && $helper->showLoginLink()): ?>
    <p class="onestepcheckout-login-link">
        <a id="onestepcheckout-login-link" href="<?php //echo $this->getUrl('customer/account/login'); ?>"><?php //echo $this->__('Already registered? Click here to login.'); ?></a>
    </p>
<?php //endif; ?>
-->

<?php if(isset($this->formErrors['unknown_source_error'])): ?>
<div class="onestepcheckout-error">
    <?php echo $this->formErrors['unknown_source_error']; ?>
</div>
<?php endif; ?>
<?php if(!$this->isCustomerLoggedIn() && $helper->showLoginLink()): ?>

<div id="onestepcheckout-login-popup-contents-login">
        <p class="onestepcheckout-numbers onestepcheckout-numbers-1">账单信息</p>
        <p class="checkout_red">如果您已经是美德因我注册用户请登录。如果您是新用户，直接输入送货信息及注册信息，继续品酒之旅。</p>
        <p class="checkout_title">已注册用户---会员登录：</p>
        <form id="onestepcheckout-login-form">

        <div id="onestepcheckout-login-loading" style="display: none;" class="loading-ajax">&nbsp;</div>
        <div id="onestepcheckout-login-error" class="onestepcheckout-error" style="display: none;">&nbsp;</div>


        <table id="onestepcheckout-login-table">
            <tr>
                <td><label style="float:right" for="id_onestepcheckout_username">E-mail或手机号：</label></td>
                <td style="text-align:right"><input tabindex="100" type="text" class="input-text" name="onestepcheckout_username" id="id_onestepcheckout_username" /></td>
                <td><span class="required">*</span><span class="note">请输入您注册时的E-mail或手机号</span></td>
            </tr>
            <tr>
                <td><label style="float:right" for="id_onestepcheckout_password"><?php echo $this->__('Password'); ?>：</label></td>
                <td><input type="password" tabindex="101" name="onestepcheckout_password" class="input-text" id="id_onestepcheckout_password" /></td>
                <td><span class="required">*</span><span class="note">请输入您的密码</span></td>
            </tr>
            <tr>
                <td>&nbsp;</td>
                <td style="text-align:right"><a style="color:#880b0b" href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>" ><?php echo $this->__('Forgotten your password?'); ?></a></td>
                <td>&nbsp;</td> 
            <tr>
                <td>&nbsp;</td>
                <td><button tabindex="102" id="onestepcheckout-login-button" type="button"><?php echo $this->__('Login'); ?></button></td>
                <td>&nbsp;</td> 
            </tr>
        </table>
        </form>
      </div>
      <div class="no_register"> 
        <p id="pay_checkout_title" class="checkout_title">未注册用户：</p>
        <div class="zjjs"><a href="#" id="pay_directly">直接结算</a> </div>

      </div>

<script>
var login_popup;
Event.observe(window, 'load', function() {

    var button = $('onestepcheckout-login-button');
    var loginButtonFunction = function(e) {

        /* Hide form and display loading */
        var table = $('onestepcheckout-login-table');
        var loading = $('onestepcheckout-login-loading');
        var error = $('onestepcheckout-login-error');

        table.hide();
        error.hide();
        loading.show();


        var form = $('onestepcheckout-login-form');
        var url = '<?php echo $this->getUrl('onestepcheckout/ajax/login', array('_secure'=>true)); ?>';
        new Ajax.Request(url, {
            parameters: form.serialize(true),
            method: 'POST',
            onComplete: function(transport) {
                if(transport.status == 200) {
                    var result = transport.responseText.evalJSON();

                    if(!result.success) {
                        loading.hide();

                        error.update(result.error);
                        error.show();

                        table.show();
                    }
                    else    {
                        // Successfully logged in user, now reload page
                        //window.location.reload(true);
                        window.location=window.location;
                    }
                }
            }
        })
    };

    var onkeypressHandler = function(event) {
        if(event.keyCode == Event.KEY_RETURN)  {
           event.preventDefault();
           loginButtonFunction();
        }
    };

    login_popup = new OneStepCheckout_Popup('onestepcheckout-login-popup','onestepcheckout-login-link', 'div#onestepcheckout-login-popup p.close a', function() {
        /* Callback for closing the popup */
        Event.stopObserving(document, 'keypress', onkeypressHandler);
    }, function() {
        /* Callback for opening the popup */
        Event.observe(document, 'keypress', onkeypressHandler);

        /* Reset error messages and state */
        $('onestepcheckout-login-error').hide();
        $('onestepcheckout-forgot-error').hide();
        $('onestepcheckout-login-popup-contents-forgot').hide();
        $('onestepcheckout-login-popup-contents-login').show();


    });

    button.observe('click', loginButtonFunction);
    $('pay_directly').observe('click', function(e)  {
        Event.stop(e);
        $('onestepcheckout-login-error').hide();
        $('onestepcheckout-login-popup-contents-login').hide();
        $('pay_directly').hide();
        $('pay_checkout_title').hide();

    });
    /*
    $('onestepcheckout-forgot-password-link').observe('click', function(e)  {
        Event.stop(e);
        $('onestepcheckout-login-error').hide();
        $('onestepcheckout-login-popup-contents-login').hide();
        $('onestepcheckout-login-popup-contents-forgot').show();

    });
    

    $('onestepcheckout-return-login-link').observe('click', function(e) {
        Event.stop(e);
        $('onestepcheckout-forgot-error').hide();
        $('onestepcheckout-login-popup-contents-forgot').hide();
        $('onestepcheckout-login-popup-contents-login').show();

    });
   

    var forgot_password_button = $('onestepcheckout-forgot-button');

    forgot_password_button.observe('click', function(e) {

        var table = $('onestepcheckout-forgot-table');
        var loading = $('onestepcheckout-forgot-loading');
        var error = $('onestepcheckout-forgot-error');
        var success = $('onestepcheckout-forgot-success');
        var email = $('id_onestepcheckout_email').getValue();

        if(email != '') {

            table.hide();
            error.hide();
            loading.show();

            var url = '<?php echo $this->getUrl('onestepcheckout/ajax/forgotPassword', array('_secure'=>true)); ?>';
            var parameters = { email: email };

            new Ajax.Request(url, {
                method: 'post',
                parameters: parameters,
                onSuccess: function(transport)  {
                    var result = transport.responseText.evalJSON();

                    if(result.success)  {
                         loading.hide();
                         success.show();
                    }
                    else    {
                        error.update('<?php echo $this->__('Please enter a registered email address.'); ?>');
                        error.show();
                        table.show();
                        loading.hide();
                    }
                }
            });

        }
        else    {
            alert('<?php echo $this->__('Please enter a valid email address'); ?>');
        }
    });
     */

});
</script>
<?php endif; ?>

 <form id="onestepcheckout-form" method="post" action="">
<div class="onestepcheckout-threecolumns checkoutcontainer onestepcheckout-skin-<?php echo $this->settings['skin']; ?> <?php if(Mage::helper('onestepcheckout')->isEnterprise()): ?>onestepcheckout-enterprise<?php endif; ?>">

    <div class="onestepcheckout-column-left">

        <div id="billing_address">
            <script type="text/javascript">
            var billing = new Billing();
            </script>
            <ul>
                <li>
                   <div class="checkout_title">填写信息：</div>
        <?php if(isset($this->formErrors['billing_error']) && count($this->formErrors['billing_errors']) > 0): ?>
        <div class="onestepcheckout-error">
            <?php echo $this->__('Please check red fields below and try again.'); ?>
        </div>
        <?php endif; ?>
        
                </li>
                <?php if ($this->customerHasAddresses()): ?>
                <li style="padding:25px">
                    <label style="width:auto;" for="billing-address-select"><?php echo $this->__('Select a billing address from your address book or enter a new address.') ?></label>
                    <div class="input-box">
                        <?php echo $this->getAddressesHtmlSelect('billing') ?>
                    </div>
                </li>
                <?php endif; ?>
                <li>
                    <div>
                        <ul id="billing_address_list" <?php echo (($this->customerHasAddresses()) ? 'style = "display:none"' : false ); ?>>

                <li class="clearfix">
                    <div class="input-box input-firstname<?php if(in_array('firstname', $this->formErrors['billing_errors'])) { echo ' input-error'; } ?>">
                        <label for="billing:firstname">收货人姓名：</label> 
                        <input class="required-entry input-text" type="text" name="billing[username]" value="<?php echo $this->getFirstname().$this->getLastname(); ?>">   <span class="required">*</span>
                        <input class="required-entry input-text" type="text" name="billing[firstname]" id="billing:firstname" value="<?php echo $this->getFirstname(); ?>" style="display:none;" /><div class="note">请输入您的姓名</div>
                    </div> 
                    <div class="input-box input-lastname<?php if(in_array('lastname', $this->formErrors['billing_errors'])) { echo ' input-error'; } ?>" style="display:none;">
                        <label for="billing:lastname"><?php echo $this->__('Last Name') ?> <span class="required">*</span></label><br />
                        <input class="required-entry input-text" type="text" name="billing[lastname]" id="billing:lastname" value="<?php echo $this->getLastname(); ?>" />
                    </div>
                    <script type="text/javascript">
                      jQuery(function($){   
                        $("input[name='billing[username]']").blur(function(){
                          var userName=$(this).val();
                            $("input[name='billing[firstname]']").val(userName.substring(0,1));
                              $("input[name='billing[lastname]']").val(userName.substring(1,userName.length));
                        })
                      })
                    </script>
                </li>
                                <li class="clearfix">
                   
                    <div class="input-box input-postcode<?php if(in_array('postcode', $this->formErrors['billing_errors'])) { echo ' input-error'; } ?>" >
                        <label for="billing:postcode"><?php echo $this->__('Zip/Postal Code') ?>：</label>
                        <input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="billing[postcode]" id="billing:postcode" value="<?php echo $this->htmlEscape($this->getPostcode()) ?>" class="validate-zip-international required-entry input-text" />   <span class="required span_hack">*</span>   <div class="note">请输入您的邮编</div>
                    </div>
                    
                </li>
  

                <?php if(!$this->isCustomerLoggedIn() || in_array('email_registered', $this->formErrors['billing_errors'])): ?>
                <li class="clearfix" id="onestepcheckout-email-error" <?php if(!in_array('email_registered', $this->formErrors['billing_errors'])): ?>style="display: none"<?php endif; ?>>
                    <div id="onestepcheckout-email-error-message" class="onestepcheckout-error">
                        <?php if(in_array('email_registered', $this->formErrors['billing_errors'])): ?>
                            <?php echo $this->__('Email address already registered. Please <a href="#" onclick="login_popup.show(); return false;">login now</a> or use a different email address.'); ?>
                        <?php else: ?>
                            <?php echo $this->__('Invalid email address.'); ?>
                        <?php endif; ?>
                    </div>
                </li>
                <?php endif; ?>


                
                <li class="fields" style="margin-top:20px">                                    
              <div class="field">                        
                <label style="margin:0 3px 0 0 !important;" for="billing:region_id" class="required">
                  <?php echo $this->__('State/Province') ?>：     
                </label>                        
                <div class="input-box">                            
                  <select id="billing:region_id" name="billing[region_id]" onchange = "selectbillcity()" title="<?php echo $this->__('State/Province') ?>" class="validate-select billregion" style="display:none;">                                 
                    <option value="">
                    <?php echo $this->__('Please select region, state or province') ?>
                    </option>                            
                  </select>                    
                <span class="required">*</span>                            
                  <script type="text/javascript">
                    //<![CDATA[
                    $('billing:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                    //]]>
                   </script>                            
                  <input type="text" id="billing:region" name="billing[region]" value="<?php echo $this->htmlEscape($this->getAddress()->getRegion()) ?>"  title="
                  <?php echo $this->__('State/Province') ?>" class="input-text" style="display:none;" />                         
                </div>                    
              </div>  
              <div class="input-box">             
                <label for="billing:city">          
                  <?php echo $this->__('City') ?>：        
                </label>                
                <select  title="<?php echo $this->__('City') ?>" name="billing[city]" onchange = "selectbilldistrict()"  class="required-entry cityoption" id="billing:city" >             
                  <option value="">
                  <?php echo $this->__('Please select city') ?>
                  </option>          
                </select> 
                <span class="required">*</span>            
              </div>  
              <div class="input-box">             
                <label for="billing:district">        
                  <?php echo $this->__('县/区') ?>：             
                </label>              
                <select  title="<?php echo $this->__('县/区') ?>" name="billing[district]" onchange = "selectdistrict()"  class="required-entry cityoption" id="billing:district" >             
                  <option value="">
                  <?php echo $this->__('Please select district') ?>
                  </option>          
                </select> 
                <span class="required">*</span>           
              </div>             
            </li>  



                <li class="clearfix" style="margin-bottom:20px">
                    <div class="input-box input-address<?php if(in_array('address', $this->formErrors['billing_errors'])) { echo ' input-error'; } ?>">
                        <label for="billing:street1">详细地址：</label>
                        <?php for ($_i=1, $_n=$this->helper('customer/address')->getStreetLines(); $_i<=$_n; $_i++): ?>
                            <input type="text" title="<?php echo $this->__('Street Address '.$_i) ?>" name="billing[street][]" id="billing:street<?php echo $_i?>" value="<?php echo $this->htmlEscape($this->getStreet($_i)) ?>" class="<?php if($_i == 1): ?>required-entry <?php endif; ?>input-text onestepcheckout-address-line" />
                            <span class="required">*</span>
                            <?php if($_i != $this->helper('customer/address')->getStreetLines()): ?><br /><?php endif; ?>
                        <?php endfor; ?>

                    </div>
                </li>
                

                <li class="clearfix" style="display:none;">
                    <div class="input-box input-country<?php if(in_array('country', $this->formErrors['billing_errors'])) { echo ' input-error'; } ?>">
                        <label for="billing:country_id"><?php echo $this->__('Country') ?> <span class="required">*</span></label>
                            <?php echo $this->getCountryHtmlSelect('billing') ?>
                    </div>
                </li>
                 
                 <li class="clearfix">
                
                                   
                    <div class="input-box input-telephone<?php if(in_array('telephone', $this->formErrors['billing_errors'])) { echo ' input-error'; } ?>">
                        <label for="billing:telephone"><?php echo $this->__('Telephone') ?>：</label>
                        <input type="text" name="billing[telephone]" value="<?php echo $this->htmlEscape($this->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="required-entry input-text" id="billing:telephone" /><span class="required">*</span><div class="note">请您输入您的电话号码</div>
                    </div>
                    
                    <?php if(!$this->isCustomerLoggedIn()): ?>
                    <p style="margin-bottom:10px">请填写您的邮箱地址，以便订单查询</p>
                    <div class="input-box input-email<?php if(in_array('email', $this->formErrors['billing_errors'])) { echo ' input-error'; } ?>">
                        <label for="billing:email"><?php echo $this->__('Email Address') ?>：</label>
                        <input type="text" name="billing[email]" id="billing:email" value="<?php echo $this->htmlEscape($this->getAddress()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="validate-email required-entry input-text" /> <span class="required">*</span><div class="note">请输入您的E-mail，作为您查询订单及跟踪的登录账户名</div>
                    </div> 
                    <?php endif ?>


                </li>
               

                
              
              





  



                <?php if($helper->showPasswords() && !$this->isCustomerLoggedIn()): ?>
                <li id="onestepcheckout-li-password" <?php if($helper->hidePasswords()): ?>style="display: none;"<?php endif; ?>>
                    <div class="input-box input-password<?php if(in_array('password', $this->formErrors['billing_errors'])) { echo ' input-error'; } ?>">
                        <label for="billing:customer_password"><?php echo $this->__('Password') ?>：</label>
                        <input type="password" class="required-entry validate-password input-text" value="<?php if(isset($_POST['billing']['customer_password'])) { echo $_POST['billing']['customer_password']; }; ?>" title="Password" id="billing:customer_password" name="billing[customer_password]"/><span class="required">*</span><div class="note">请您输入您的密码，以防个人信息及订单信息泄露</div>
                    </div>
                    <br />
                    <div style="display:none;" class="input-box input-password<?php if(in_array('confirm_password', $this->formErrors['billing_errors'])) { echo ' input-error'; } ?>">
                        <label for="billing:confirm_password"><?php echo $this->__('Confirm password') ?>：</label>
                        <input type="password" class="required-entry validate-password input-text" value="<?php if(isset($_POST['billing']['confirm_password'])) { echo $_POST['billing']['confirm_password']; }; ?>" id="billing:confirm_password" title="Confirm Password" name="billing[confirm_password]"/>
                    </div>
                    <script type="text/javascript">
  jQuery(function($){   
    $("input[name='billing[customer_password]']").blur(function(){
      var userName=$(this).val();
      $("input[name='billing[confirm_password]']").val(userName);
    })
  })
</script>
                </li>
                <?php endif; ?>
                            <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
                            <li class="control" style="padding-left: 47px;
    padding-top: 20px;">
                                <input style="float:left;border:0 none;margin-top:5px;" type="checkbox" name="billing[save_in_address_book]" value="1" title="<?php echo $this->__('Save in address book') ?>" id="billing:save_in_address_book" onchange="shipping.setSameAsBilling(false);"<?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox" /><label style="float:left;width:auto" for="billing:save_in_address_book"><?php echo $this->__('Save in address book') ?></label>
                            </li>
                            <?php else:?>
                            <li class="no-display"><input type="hidden" name="billing[save_in_address_book]" value="1" /></li>
                            <?php endif; ?>
                        </ul>

                    </div>
                </li>
                <?php if($this->differentShippingAvailable()): ?>
                <li class="clearfix">
                    <div class="input-box input-different-shipping">
                            <input type="checkbox" name="billing[use_for_shipping]" id="billing:use_for_shipping_yes" value="1" <?php if($this->sameAsBilling()) { echo ' checked="checked" '; } ?>  />
                            <label for="billing:use_for_shipping_yes"><?php echo $this->__('Ship to the same address'); ?></label>
                    </div>
                </li>
                <?php else: ?>
                <li class="clearfix">
                    <input type="hidden" name="billing[use_for_shipping]" id="billing:use_for_shipping_yes" value="1" />
                </li>
                <?php endif; ?>
            </ul>
        </div>
<?php if($this->differentShippingAvailable()): ?>
<div id="shipping_address" <?php  echo (($this->sameAsBilling()) ? 'style="display: none"': false);?>>
    <script type="text/javascript">
        var shipping = new Shipping();
    </script>
    <ul>
                    <li class="shipping-address-title">
                        <?php echo $this->__('Shipping address'); ?>
                    </li>
        <?php if ($this->customerHasAddresses()): ?>
       <li class="form-alt">
           <label for="shipping-address-select"><?php echo $this->__('Select a shipping address from your address book or enter a new address.') ?></label>
           <div class="input-box"><?php echo $this->getAddressesHtmlSelect('shipping') ?></div>
       </li>
        <?php endif ?>
        <li id="shipping_address_list" <?php if($this->sameAsBilling() || $this->customerHasAddresses()) { echo '  style="display: none;" '; } ?>>
            <div id="">
                <ul>
                    <li>
                        <div class="input-box input-firstname<?php if(in_array('firstname', $this->formErrors['shipping_errors'])) { echo ' input-error'; } ?>">
                            <label for="shipping:firstname"><?php echo $this->__('First Name') ?> <span class="required">*</span></label><br />
                            <input class="required-entry input-text" type="text" name="shipping[firstname]" id="shipping:firstname" value="<?php echo $this->getShippingFirstname(); ?>" />
                        </div>
                        <div class="input-box input-lastname<?php if(in_array('lastname', $this->formErrors['shipping_errors'])) { echo ' input-error'; } ?>">
                            <label for="shipping:lastname"><?php echo $this->__('Last Name') ?> <span class="required">*</span></label><br />
                            <input class="required-entry input-text" type="text" name="shipping[lastname]" id="shipping:lastname" value="<?php echo $this->getShippingLastname(); ?>" />
                        </div>
                    </li>
                    <li class="clearfix">
                        <div class="input-box input-address<?php if(in_array('address', $this->formErrors['shipping_errors'])) { echo ' input-error'; } ?>">
                            <label for="shipping:street1"><?php echo $this->__('Address'); ?> <span class="required">*</span></label><br />
                            <?php for ($_i=1, $_n=$this->helper('customer/address')->getStreetLines(); $_i<=$_n; $_i++): ?>
                                    <input type="text" title="<?php echo $this->__('Street Address '.$_i) ?>" name="shipping[street][]" id="shipping:street<?php echo $_i?>" value="<?php echo $this->htmlEscape($this->getShippingStreet($_i)) ?>" class="input-text onestepcheckout-address-line" />
                            <?php endfor ?>
                        </div>
                    </li>
                    <li class="clearfix">
                        <div class="input-box input-country<?php if(in_array('country', $this->formErrors['shipping_errors'])) { echo ' input-error'; } ?>">
                            <label for="shipping:country_id"><?php echo $this->__('Country') ?> <span class="required">*</span></label><br />
                                <?php echo $this->getCountryHtmlSelect('shipping') ?>
                        </div>
                    </li>
                    <?php if(!$this->settings['exclude_city']):?>
                    <li class="clearfix">
                        <div class="input-box input-city<?php if(in_array('city', $this->formErrors['shipping_errors'])) { echo ' input-error'; } ?>">
                            <label for="shipping:city"><?php echo $this->__('City') ?> <span class="required">*</span></label><br/>
                            <input type="text" name="shipping[city]" value="<?php echo $this->htmlEscape($this->getShippingCity()) ?>" title="<?php echo $this->__('City') ?>" class="required-entry input-text" id="shipping:city" />
                        </div>
                    </li>
                    <?php endif; ?>
                    <?php if(!($this->settings['exclude_zip'] && $this->settings['exclude_region'])): ?>
                    <li class="clearfix">
                        <?php if(!$this->settings['exclude_zip']): ?>
                        <div class="input-box input-postcode<?php if(in_array('postcode', $this->formErrors['shipping_errors'])) { echo ' input-error'; } ?>" >
                            <label for="shipping:postcode"><?php echo $this->__('Zip/Postal Code') ?> <span class="required">*</span></label><br />
                            <input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="shipping[postcode]" id="shipping:postcode" value="<?php echo $this->htmlEscape($this->getShippingPostcode()) ?>" class="validate-zip-international required-entry input-text" />
                        </div>
                        <?php endif; ?>
                       
                    </li>
                    <?php endif; ?>
                    <li class="clearfix">
                        <?php if(!$this->settings['exclude_telephone']):?>
                        <div class="input-box input-telephone<?php if(in_array('telephone', $this->formErrors['shipping_errors'])) { echo ' input-error'; } ?>">
                            <label for="shipping:telephone"><?php echo $this->__('Telephone') ?> <span class="required">*</span></label><br/>
                            <input type="text" name="shipping[telephone]" value="<?php echo $this->htmlEscape($this->getShippingTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="required-entry input-text" id="shipping:telephone" />
                        </div>
                        <?php endif; ?>
                    </li>
                    <?php if(!($this->settings['exclude_company'] && $this->settings['exclude_fax'])): ?>
                    <li class="clearfix">
                        <?php if(!$this->settings['exclude_company']): ?>
                        <div class="input-box input-company<?php if(in_array('company', $this->formErrors['shipping_errors'])) { echo ' input-error'; } ?>">
                            <label for="shipping:company"><?php echo $this->__('Company') ?></label><br />
                            <input type="text" name="shipping[company]" value="<?php echo $this->htmlEscape($this->getShippingCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text" id="shipping:company" />
                        </div>
                        <?php endif; ?>
                        <?php if(!$this->settings['exclude_fax']): ?>
                        <div class="input-box input-fax<?php if(in_array('fax', $this->formErrors['shipping_errors'])) { echo ' input-error'; } ?>">
                            <label for="shipping:fax"><?php echo $this->__('Fax') ?></label><br />
                            <input type="text" name="shipping[fax]" value="<?php echo $this->htmlEscape($this->getShippingFax()) ?>" title="<?php echo $this->__('Fax') ?>" class="input-text" id="shipping:fax" />
                        </div>
                        <?php endif; ?>
                    </li>
                    <?php endif; ?>
                    <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
                    <li>
                    <div class="input-box input-saveaddress">
                        <input type="checkbox" name="shipping[save_in_address_book]" value="1" title="<?php echo $this->__('Save in address book') ?>" id="shipping:save_in_address_book" onchange="shipping.setSameAsBilling(false);"<?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox" /><label for="shipping:save_in_address_book"><?php echo $this->__('Save in address book') ?></label></div></li>
                    <?php else:?>
                    <li class="no-display">
                        <input type="hidden" name="shipping[save_in_address_book]" value="1" /></li>
                    <?php endif;?>
                </ul>
                    <input type="hidden" name="shipping[address_id]" value="<?php echo $this->getQuote()->getShippingAddress()->getId() ?>" id="shipping:address_id" />
                    <!-- END LIST OF SHIPPIING FIELDS -->
    </div>
        </li>
    </ul>
</div>
<?php endif; ?>
</div>

    <div class="onestepcheckout-column-middle">


        <?php if(!$this->isVirtual()): ?>
            <div class="onestepcheckout-shipping-method">
                <p class="onestepcheckout-numbers onestepcheckout-numbers-<?php echo $step_counter++; ?>"><?php echo $this->__('Shipping method'); ?></p>

                <?php if(isset($this->formErrors['shipping_method']) && $this->formErrors['shipping_method']): ?>
                <div class="onestepcheckout-error onestepcheckout-shipment-method-error">
                    <?php echo $this->__('Please choose a shipping method.'); ?>
                </div>
                <?php endif; ?>

                <div class="onestepcheckout-shipping-method-block">
                    <?php echo $this->getChildHtml('choose-shipping-method'); ?>
                </div>
            </div>
        <?php endif; ?>

        <p class="onestepcheckout-numbers onestepcheckout-numbers-<?php echo $step_counter++; ?>"><?php echo $this->__('Payment method'); ?></p>

        <?php if(isset($this->formErrors['payment_method']) && $this->formErrors['payment_method']): ?>
        <div class="onestepcheckout-error onestepcheckout-payment-method-error">
            <?php echo $this->__('Please choose a payment method.'); ?>
        </div>
        <?php else: ?>
        <?php if(isset($this->formErrors['payment_method_error'])): ?>
            <div class="onestepcheckout-error onestepcheckout-payment-method-error">
                <?php echo $this->__('Please enter valid details below.'); ?>
            </div>
        <?php endif; ?>
        <?php endif; ?>

        <?php echo $this->getChildHtml('choose-payment-method'); ?>

        <div class="tool-tip" id="payment-tool-tip" style="display:none;">
            <div class="btn-close">
                <a href="#" id="payment-tool-tip-close"><img src="<?php echo $this->getSkinUrl('images/btn_window_close.gif') ?>" alt="<?php echo $this->__('Close') ?>" /></a>
            </div>
            <div class="block-content">
            <img src="<?php echo $this->getSkinUrl('images/cvv.gif') ?>" alt="<?php echo $this->__('Card Verification Number Visual Reference') ?>" />
            </div>
        </div>

    </div>

    <div class="onestepcheckout-column-right">

        <p class="onestepcheckout-numbers onestepcheckout-numbers-4"><?php echo $this->__('Review your order'); ?></p>

        <div class="onestepcheckout-summary">
            <?php echo $this->getChildHtml('summary'); ?>
        </div>

        <?php if($this->settings['enable_discount']): ?>
        <div class="onestepcheckout-coupons">
            <?php $_couponcode = $this->getQuote()->getCouponCode(); ?>
            <label for="id_couponcode"><?php echo $this->__('Coupon code:'); ?></label><br/>
            <input style="margin-top:5px; width:95%;" type="text" name="onestepcheckout-couponcode" id="id_couponcode" value="<?php echo $_couponcode; ?>" />
            <br/>
            <button id="onestepcheckout-coupon-add" class="form-button-alt" type="button"><?php echo $this->__('Apply Coupon'); ?></button>
            <button id="onestepcheckout-coupon-remove" class="form-button-alt" type="button" style="<?php if($_couponcode == '') { echo 'display: none;'; } ?>"><?php echo $this->__('Cancel Coupon'); ?></button>
            <script>
            document.observe('dom:loaded', function() {
                $('onestepcheckout-coupon-add').observe('click', function(e)    {
                    var coupon = $('id_couponcode').getValue();

                    if(coupon == '')    {
                        alert('<?php echo $this->__('Please enter a valid coupon code.'); ?>');
                        return;
                    }

                    var url = '<?php echo $this->getUrl('onestepcheckout/ajax/add_coupon', array('_secure'=>true)); ?>';
                    var parameters = {code: coupon};
                    var summary = $$('div.onestepcheckout-summary').first();

                    summary.update('<div class="loading-ajax">&nbsp;</div>');

                    new Ajax.Request(url, {
                        method: 'post',
                        parameters: parameters,
                        onSuccess: function(transport)  {
                            if(transport.status == 200) {
                                var response = transport.responseText.evalJSON();

                                if(response.success)    {
                                    summary.update(response.summary);
                                    /* Show remove button */
                                    $('onestepcheckout-coupon-remove').show();
                                }
                                else    {
                                    summary.update(response.summary);
                                    alert(response.error);
                                    /* Hide remove button */
                                    $('onestepcheckout-coupon-remove').hide();
                                }


                            }
                        }
                    });
                });

                $('onestepcheckout-coupon-remove').observe('click', function(e) {
                    var coupon = $('id_couponcode').getValue();
                    var url = '<?php echo $this->getUrl('onestepcheckout/ajax/add_coupon', array('_secure'=>true)); ?>';
                    var parameters = {code: coupon, remove: '1'};
                    var summary = $$('div.onestepcheckout-summary').first();

                    summary.update('<div class="loading-ajax">&nbsp;</div>');

                    new Ajax.Request(url, {
                        method: 'post',
                        parameters: parameters,
                        onSuccess: function(transport)  {
                            if(transport.status == 200) {
                                var response = transport.responseText.evalJSON();

                                if(response.success)    {
                                    $('onestepcheckout-coupon-remove').hide();
                                }

                                var summary = $$('div.onestepcheckout-summary').first();
                                summary.hide();
                                summary.update(response.summary);
                                summary.show();
                            }
                        }
                    });
                });
            });
            </script>
        </div>
        <?php endif; ?>


        <?php if($this->settings['enable_comments']): ?>
            <div class="onestepcheckout-comments">
                <label for="id_comments"><?php echo $this->__('Comments'); ?></label><br />
                <textarea id="id_comments" name="onestepcheckout_comments"><?php if(isset($_POST['onestepcheckout_comments'])) { echo $_POST['onestepcheckout_comments']; } ?></textarea>
            </div>
        <?php endif; ?>

        <?php if($this->settings['enable_gift_messages']): ?>
            <div class="onestepcheckout-giftmessagecontainer">
            <?php echo $this->helper('onestepcheckout/message')->getInline('onepage_checkout', $this->getQuote(), $this->getDontDisplayContainer()) ?>
            </div>
        <?php endif; ?>

        <?php if($this->settings['enable_newsletter'] && $this->settings['enable_terms']): ?>
            <div class="onestepcheckout-enable-newsletter">
                <input type="checkbox" id="id_subscribe_newsletter" name="subscribe_newsletter" value="1" <?php if($this->settings['newsletter_default_checked']): ?>checked="checked"<?php endif; ?> />
                <label for="id_subscribe_newsletter"><?php echo $this->__('Subscribe to our newsletter'); ?></label>
            </div>
        <?php endif; ?>

        <?php if($this->settings['enable_terms']): ?>
            <div class="onestepcheckout-enable-terms">
                <?php

                if(isset($this->formErrors['terms_error']) && $this->formErrors['terms_error']) {
                    $terms_error = true;
                }
                else    {
                    if($_SERVER['REQUEST_METHOD'] == 'POST')    {
                        $terms_error = false;
                    }
                    else    {
                        $terms_error = true;
                    }
                }
                ?>

                <input class="required-entry" type="checkbox" id="id_accept_terms" name="accept_terms" value="1" <?php if(!$terms_error) echo "checked=\"checked\""; ?> />
                <label for="id_accept_terms"><?php echo $this->__('I accept the <a id="onestepcheckout-toc-link" target="_blank" href="#">Terms and Conditions</a>'); ?></label>

                <?php if(isset($this->formErrors['terms_error']) && $this->formErrors['terms_error']): ?>
                <div class="onestepcheckout-error onestepcheckout-terms-error">
                    <?php echo $this->__('You must accept our terms to continue.'); ?>
                </div>
                <?php endif; ?>

            </div>
        <?php endif; ?>

        <div class="onestepcheckout-place-order">
            <input id="onestepcheckout-place-order" type="button" />
        </div>



        <?php if($this->settings['enable_newsletter'] && !$this->settings['enable_terms']): ?>
            <div class="onestepcheckout-enable-newsletter-bottom">
                <input type="checkbox" id="id_subscribe_newsletter" name="subscribe_newsletter" value="1" <?php if($this->settings['newsletter_default_checked']): ?> checked="checked" <?php endif; ?> />
                <label for="id_subscribe_newsletter"><?php echo $this->__('Subscribe to our newsletter'); ?></label>
            </div>
        <?php endif; ?>

    </div>

    <div style="clear: both;">&nbsp;</div>

</div>

</fieldset>



</form>

















<?php if($helper->isValidateEmail()): ?>
<script>
$('billing:email').observe('blur', function(e)    {
    var url = '<?php echo $this->getUrl('onestepcheckout/ajax/check_email', array('_secure'=>true)); ?>';
    var email = e.element().getValue();
    var parameters = { email: email };

    new Ajax.Request(url, {
        parameters: parameters,
        onComplete: function(response)  {
            if(response.status == 200)  {
                var result = response.responseText.evalJSON().result;
                if(result == 'invalid') {
                    $('onestepcheckout-email-error-message').update('<?php echo $this->__('Invalid email address.'); ?>');
                    $('onestepcheckout-email-error').show();
                }
                else if(result == 'exists') {
                    <?php if($this->settings['registration_order_without_password']): ?>
                    // Remove the password fields if the email exists in database
                    $('onestepcheckout-li-password').hide();
                    <?php else: ?>

                    $('onestepcheckout-email-error-message').update('<?php echo $this->__('Email address already registered. Please <a href="#" onclick="login_popup.show(); return false;">login now</a> or use a different email address.'); ?>');
                    $('onestepcheckout-email-error').show();
                    // Ask the user to login or change email address
                    //login_popup.show();
                    $('id_onestepcheckout_username').value = email;
                    <?php endif; ?>
                }
                else    {
                    $('onestepcheckout-email-error').hide();
                    $('onestepcheckout-li-password').show();
                }
            }
        }
    })

});
</script>
<?php endif; ?>





<?php if($this->settings['enable_terms']): ?>
<div id="onestepcheckout-toc-popup" style="display: none;">

    <div class="onestepcheckout-popup-wrapper">
        <div class="onestepcheckout-popup-wrapper-inner">
            <h1><?php echo $this->settings['terms_title']; ?></h1>

            <div class="onestepcheckout-toc-terms">
                <?php echo $this->settings['terms_contents']; ?>
            </div>

            <p class="close"><a href="#"><?php echo $this->__('Close'); ?></a></p>
        </div>
    </div>
    <div class="onestepcheckout-popup-footer">&nbsp;</div>
</div>
<script>
var popup;
Event.observe(window, 'load', function() {
    popup = new OneStepCheckout_Popup('onestepcheckout-toc-popup','onestepcheckout-toc-link', 'div#onestepcheckout-toc-popup p.close a');
});
</script>
<?php endif; ?>





<script>
<?php if($this->hasFormErrors()): ?>
if($$('div.input-error').length > 0) {
    var input = $$('div.input-error')[0].select('input');
    if(input.length == 1)   {
        input[0].focus();
    }
}
<?php endif; ?>
</script>

<?php if(!$this->settings['exclude_region']): ?>
<script type="text/javascript">countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?></script>
<script type="text/javascript">
//<![CDATA[
    var billingRegionUpdater = new RegionUpdater('billing:country_id', 'billing:region', 'billing:region_id', countryRegions);

    <?php if($this->settings['enable_different_shipping'] && !$this->isVirtual()): ?>
    var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', countryRegions);
    <?php endif; ?>
//]]>
</script>
<?php endif; ?>

<script type="text/javascript">

document.observe('dom:loaded', function() {

    if ($$('div.shopping-cart-totals').length == 1) {
    }
    else    {

        /* Fix issue with bad centering due to parent */
        $(document.body).insert($('onestepcheckout-login-popup'));
        $(document.body).insert($('onestepcheckout_popup_overlay'));
        $(document.body).insert($('onestepcheckout-toc-popup'));

        /* Handle place order click event */
        $('onestepcheckout-place-order').observe('click', function(e)   {


            // First validate the form
            var form = new VarienForm('onestepcheckout-form');

            if(!form.validator.validate())  {
                Event.stop(e);
            }
            else    {
                /* Disable button to avoid multiple clicks */
                var element = e.element();
                element.disabled = true;

                /* Submit the form */
                $('onestepcheckout-form').submit();
            }
        });


        // This is a separate page
        var url = '<?php echo $this->getUrl('onestepcheckout/ajax/set_methods_separate', array('_secure'=>true)); ?>';
        var update_payments = <?php echo $this->settings['enable_update_payment_on_shipping'] ? 'true' : 'false'; ?>;

        $$('dl.shipment-methods input').invoke('observe', 'click', get_separate_save_methods_function(url, update_payments));
        $$('div.payment-methods input[name^=payment\[method\]]').invoke('observe', 'click', get_separate_save_methods_function(url));

        $$('div.payment-methods input[name^=payment\[method\]]').invoke('observe', 'click', function() {
            $$('div.onestepcheckout-payment-method-error').each(function(item) {
                new Effect.Fade(item);
            });
        });

        $$('dl.shipment-methods input').invoke('observe', 'click', function() {
            $$('div.onestepcheckout-shipment-method-error').each(function(item) {
                new Effect.Fade(item);
            });
        });

        var has_hidden_terms = false;

        if($('id_accept_terms') != null)    {

            $('id_accept_terms').observe('click', function(e)   {
                var element = e.element();

                if(element.checked) {
                    $$('div.onestepcheckout-terms-error').each(function(item) {
                        new Effect.Fade(item);
                        has_hidden_terms = true;
                    });
                }
                else    {
                    if(has_hidden_terms)    {
                        $$('div.onestepcheckout-terms-error').each(function(item) {
                            new Effect.Appear(item);
                            has_hidden_terms = false;
                        });
                    }
                }
            });
        }
    }

    var form = $('onestepcheckout-form');

    /* Highlight selected payment method if one set */
    if($RF(form, 'payment[method]') != null)    {
        try {
            var payment_method = $RF(form, 'payment[method]');
            $('container_payment_method_' + payment_method).show();
            $('payment_form_' + payment_method).show();
        } catch(err)    {

        }
    }

    /* Set default shipping method if not set */
    if($RF(form, 'shipping_method') == null)    {
        try {
            var method = '<?php echo $this->_getDefaultShippingMethod(); ?>';
            if(method != '')    {
                $('s_method_' + method).checked = true;
                get_separate_save_methods_function(url)();
            }
        } catch(err)    {

        }
    }

   get_separate_save_methods_function(url)();

<?php if($this->differentShippingAvailable()): ?>
    $('billing:use_for_shipping_yes').observe('click', function(e)  {
        var element = e.element();
        if(element.getValue() == "1"){
            $('shipping_address').hide();
        } else {
            if($('shipping-address-select') && $('shipping-address-select').value == ''){
                $('shipping_address_list').show()
            }
            $('shipping_address').show();
            <?php if(!$this->isCustomerLoggedIn()):?>
            $('shipping_address_list').show()
            <?php endif;?>
        }

        <?php if($this->settings['enable_ajax_save_billing']): ?>
        get_save_billing_function('<?php echo $this->getUrl('onestepcheckout/ajax/save_billing', array('_secure'=>true)); ?>', '<?php echo $this->getUrl('onestepcheckout/ajax/set_methods_separate', array('_secure'=>true)); ?>', <?php echo $this->settings['enable_update_payment_on_shipping'] ? 'true' : 'false'; ?>)();
        <?php endif; ?>

    });
    <?php endif; ?>

    <?php if($this->settings['enable_ajax_save_billing']): ?>

    var url_save_billing = '<?php echo $this->getUrl('onestepcheckout/ajax/save_billing', array('_secure'=>true)); ?>';
    var url_set_methods = '<?php echo $this->getUrl('onestepcheckout/ajax/set_methods_separate', array('_secure'=>true)); ?>';
    var update_payments = <?php echo $this->settings['enable_update_payment_on_shipping'] ? 'true' : 'false'; ?>;
    var update_on_initial = false;


    <?php if($this->hasAjaxSaveBillingField('country')): ?>

        $('billing:country_id').observe('change', get_save_billing_function(url_save_billing, url_set_methods,update_payments));

        <?php if($this->differentShippingAvailable()): ?>
        $('shipping:country_id').observe('change', get_save_billing_function(url_save_billing, url_set_methods, update_payments));
            <?php if($this->isCustomerLoggedIn()): ?>
            Event.stopObserving('shipping-address-select', 'change');
            $('shipping-address-select').observe('change', get_save_billing_function(url_save_billing, url_set_methods,update_payments));
            <?php endif; ?>
        <?php endif; ?>
        <?php if($this->isCustomerLoggedIn()): ?>
        Event.stopObserving('billing-address-select', 'change');
        $('billing-address-select').observe('change', get_save_billing_function(url_save_billing, url_set_methods,update_payments));
        <?php endif; ?>
    <?php endif; ?>


    <?php if($this->hasAjaxSaveBillingField('state/region')): ?>
    $('billing:region_id').observe('change', get_save_billing_function(url_save_billing, url_set_methods,update_payments));
    $('billing:region').observe('change', get_save_billing_function(url_save_billing, url_set_methods,update_payments));

        <?php if($this->differentShippingAvailable()): ?>
        $('shipping:region_id').observe('change', get_save_billing_function(url_save_billing, url_set_methods,update_payments));
        $('shipping:region').observe('change', get_save_billing_function(url_save_billing, url_set_methods,update_payments));
            <?php if($this->isCustomerLoggedIn()): ?>
            Event.stopObserving('shipping-address-select', 'change');
            $('shipping-address-select').observe('change', get_save_billing_function(url_save_billing, url_set_methods,update_payments));
            <?php endif; ?>
        <?php endif; ?>
        <?php if($this->isCustomerLoggedIn()): ?>
        Event.stopObserving('billing-address-select', 'change');
        $('billing-address-select').observe('change', get_save_billing_function(url_save_billing, url_set_methods,update_payments));
        <?php endif; ?>

    <?php endif; ?>



    <?php if($this->hasAjaxSaveBillingField('postcode')): ?>
    $('billing:postcode').observe('change', get_save_billing_function(url_save_billing, url_set_methods,update_payments));

        <?php if($this->differentShippingAvailable()): ?>
        $('shipping:postcode').observe('change', get_save_billing_function(url_save_billing, url_set_methods,update_payments));
            <?php if($this->isCustomerLoggedIn()): ?>
            Event.stopObserving('shipping-address-select', 'change');
            $('shipping-address-select').observe('change', get_save_billing_function(url_save_billing, url_set_methods,update_payments));
            <?php endif; ?>
        <?php endif; ?>
        <?php if($this->isCustomerLoggedIn()): ?>
        Event.stopObserving('billing-address-select', 'change');
        $('billing-address-select').observe('change', get_save_billing_function(url_save_billing, url_set_methods,update_payments));
        <?php endif; ?>

    <?php endif; ?>

    <?php if($this->hasAjaxSaveBillingField('city')): ?>
    $('billing:city').observe('change', get_save_billing_function(url_save_billing, url_set_methods,update_payments));

        <?php if($this->differentShippingAvailable()): ?>
        $('shipping:city').observe('change', get_save_billing_function(url_save_billing, url_set_methods,update_payments));
            <?php if($this->isCustomerLoggedIn()): ?>
            Event.stopObserving('shipping-address-select', 'change');
            $('shipping-address-select').observe('change', get_save_billing_function(url_save_billing, url_set_methods,update_payments));
            <?php endif; ?>
        <?php endif; ?>
        <?php if($this->isCustomerLoggedIn()): ?>
        Event.stopObserving('billing-address-select', 'change');
        $('billing-address-select').observe('change', get_save_billing_function(url_save_billing, url_set_methods,update_payments));
        <?php endif; ?>

    <?php endif; ?>


    <?php endif; ?>



    if($('payment-tool-tip-close')){
        Event.observe($('payment-tool-tip-close'), 'click', toggleToolTip);
    }

    $$('.cvv-what-is-this').each(function(element){
        Event.observe(element, 'click', toggleToolTip);
    });


});

function toggleToolTip(event){
    if($('payment-tool-tip')){
        $('payment-tool-tip').setStyle({
            left: (Event.pointerX(event)-100)+'px',
            top: (Event.pointerY(event)-300)+'px'
        });
        $('payment-tool-tip').toggle();
    }
    Event.stop(event);
}

</script>

<?php endif; ?>

<div id="onestepcheckout_popup_overlay" style="display: none;">&nbsp;</div>
<script type="text/javascript">
jQuery(document).ready(function(){
	jQuery("span.span_hack").show();
})
</script>
<script type="text/javascript">
jQuery(document).ready(function() {
    selectbillcity();
});
</script> 