<h2><a href="<?php echo $this->getUrl('news/cat/health');?>">健康养生</a></h2>
<?php if ($posts = $this->getCatPosts(5)): ?>  
<ul class="notice_list">
     <?php $i=0; foreach ($posts as $post): ?>
     <?php 
     $i++; 
     if ($i > 4){
         break;
     } ?>    
<li><a href="<?php echo $post->getAddress(); ?>"> <?php echo mb_substr($post->getTitle(), 0, 12, 'utf-8'); ?> </a></li>
      <?php endforeach; ?>

</ul>
<?php endif; ?>


<script type="text/javascript">  
jQuery(document).ready(function(){
jQuery(".notice_list li").addClass(function() {
	return 'item_' + jQuery(this).index();
});
})
</script>





