<div class="blog_jjdg">
<h2>荐酒导购</h2>
<?php if ($posts = $this->getCatPosts(2)): ?>  
<ul class="notice_list">
    <?php $i=0; foreach ($posts as $post): ?>
    <?php 
        $i++; 
        if ($i > 10){
            break;
        } 
    ?>    
        <li><a href="<?php echo $post->getAddress(); ?>"> <?php echo mb_substr($post->getTitle(), 0, 12, 'utf-8'); ?> </a></li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>
</div>


<script type="text/javascript">  
jQuery(document).ready(function(){
jQuery(".notice_list li").addClass(function() {
	return 'item_' + jQuery(this).index();
});
})
</script>





