<?php $post = $this->getPost();?>  
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="postWrapper">
	<div class="postTitle">
        <h2><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle();?></a></h2>
		<h3><?php echo $post->getCreatedTime(); ?></h3>
    </div>
	
	<div class="postContent"><?php echo $post->getPostContent(); ?></div>
	<?php echo $this->getBookmarkHtml($post) ?>
	<div class="tags"><?php echo Mage::getBlockSingleton('blog/blog')->getTagsHtml($post) ?></div>
</div>
