
<?php $blog_id = $this->getBlogId(); ?>
<?php $posts = $this->getCatPosts($blog_id) ?>  
<div class="col_left">
  <ul class="blog_main">
      <?php $i = 0; foreach ($posts as $post): ?>
          <?php if($i%10 == 0): ?>
            <li>
                <ul>
          <?php endif; ?>
              <li>
                  <span><?php echo $post->getCreatedTime(); ?></span>
                  <a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle();?></a>
              </li>
          <?php if($i%10 == 9): ?>
              </ul>
              <?php break;?>
            </li>
          <?php endif; ?>
          <?php $i++; ?>
      <?php endforeach; ?>
  </ul>
</div>




