 <?php if ($posts = $this->getCatPosts(18)): ?> 
                                                                 <div class="ysbj_right">
<div class="Romantic_content">
<h1><span>饮酒禁忌</span> <img src="<?php echo $this->getUrl().'media/yjjj_title.gif';?>" alt="" /></h1>
<div class="R_content">
            <?php $i=0; foreach ($posts as $post): ?>
         <?php 
     $i++; 
     if ($i > 1){
         break;
     } ?> 
<div class="R_top">
<ul>
<li> <img src="<?php echo $this->getUrl().'media/yjjj_pic'.$i.'.gif';?>" alt="" /> </li>
<li class="desc"><a href="<?php echo $post->getAddress(); ?>">
<h5><?php echo mb_substr($post->getTitle(), 0, 10, 'utf-8'); ?></h5>
</a>
<p><?php echo mb_substr($post->getPostContent(), 0, 52, 'utf-8'); ?>&hellip;&hellip;</p>
</li>
</ul>
</div>
<?php endforeach; ?>
<div class="R_bottom">
<ul>
       <?php $i=0; foreach ($posts as $post): ?>
               <?php 
     $i++; 
          if ($i <= 1){
         continue;;
     }
     if ($i > 6){
         break;
     } ?> 
<li> <span class="author"> <a href="<?php echo $post->getAddress(); ?>" target="_blank"><?php echo mb_substr($post->getCreatedTime(),0,10,'utf-8'); ?></a> </span> <a href="<?php echo $post->getAddress(); ?>" target="_blank"><?php echo mb_substr($post->getTitle(), 0, 16, 'utf-8'); ?> </a> </li>
<?php endforeach; ?>

</ul>
</div>
</div>
</div>
</div>
<?php endif; ?>